name: Build and Deploy Jekyll Site to Master

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Set up Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        bundler-cache: true

    # 3. Install dependencies
    - name: Install Dependencies
      run: bundle install

    # 4. Build the Jekyll site with debugging
    - name: Build Jekyll Site
      run: |
        bundle exec jekyll build --trace --verbose
        ls -al _site  # List contents of the _site directory

    # 5. Deploy built site to master
    - name: Deploy Built Site
      run: |
        mv _site/* ./          # Move the built site to the root directory
        touch .nojekyll        # Disable Jekyll processing on GitHub Pages
      env:
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
    - name: Commit and Push Changes
      run: |
        git add --all
        git commit -m "Deploy built site [skip ci]" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}